# Generated by Django 6.0.2 on 2026-02-23 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelroom',
            name='hotel_description',
        ),
    ]
